{"uuid":"0f0ee28b-6177-439b-957d-b097871f11be","historyId":"f9845a563bcfc047440244d3ee6a3cf5","fullName":"contact.ContactTests.test_to_submit_message_negative_email","labels":[{"name":"package","value":"contact.ContactTests"},{"name":"testClass","value":"contact.ContactTests"},{"name":"testMethod","value":"test_to_submit_message_negative_email"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"AutomationAssessment"},{"name":"subSuite","value":"contact.ContactTests"},{"name":"host","value":"ndi-mb-259"},{"name":"thread","value":"10263@ndi-mb-259.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"owner","value":"Varun Chawla"},{"name":"story","value":"STORY 1"},{"name":"feature","value":"FEATURE 1"},{"name":"epic","value":"EPIC 1"},{"name":"severity","value":"normal"}],"links":[],"name":"test_to_submit_message_negative_email","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"We are on the correct website. expected [true] but found [false]","trace":"java.lang.AssertionError: We are on the correct website. expected [true] but found [false]\n\tat org.testng.Assert.fail(Assert.java:110)\n\tat org.testng.Assert.failNotEquals(Assert.java:1413)\n\tat org.testng.Assert.assertTrue(Assert.java:56)\n\tat contact.ContactTests.test_to_submit_message_negative_email(ContactTests.java:87)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:808)\n\tat org.testng.TestRunner.run(TestRunner.java:603)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:429)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:326)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1169)\n\tat org.testng.TestNG.runSuites(TestNG.java:1092)\n\tat org.testng.TestNG.run(TestNG.java:1060)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\n"},"stage":"finished","description":"Tests that the user cannot submit a message with 'invalid email input', to www.seleniumframework.com via their 'contact' page.","steps":[],"attachments":[],"parameters":[],"start":1643011297232,"stop":1643011303262}